---
:global:
  python_min_version: "3.11"
  python_supported_versions: ["3.11", "3.12", "3.13", "3.14"]
  module_rootname: "django_datawatch"
  module_description: "Automated data checks for Django"
  module_keywords: ["django", "monitoring", "datawatch", "check", "checks"]
  dependencies:
    [
      "celery>=5.6.0",
      "Django>=5.2,<6.2",
      "django-extensions>=4.1",
      "django-model-utils>=5.0.0",
      "python-dateutil>=2.9.0",
    ]
  max_line_length: 120
  changelog_since_tag: "6.0.0"

.devcontainer/devcontainer.json:
  run_services: ["app", "db", "rabbitmq"]

compose.yaml:
  unmanaged: true
