---
:global:
  module_rootname: "django_datawatch"
  module_description: "Automated data checks for Django"
  module_keywords: ["django", "monitoring", "datawatch", "check", "checks"]
  dependencies:
    [
      "celery>=5.0.0",
      "Django>=4.2,<6.0",
      "django-extensions>=3.0.0",
      "django-model-utils>=4.2.0",
      "python-dateutil>=2.8.0",
    ]
  max_line_length: 120

compose.yaml:
  unmanaged: true
