services:
  app:
    build:
      context: .
    user: app
    entrypoint: /app/manage.py
    command: runserver 0:8000
    volumes:
      - .:/app:cached
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
    restart: unless-stopped
    networks:
      default:
        aliases:
          - datawatch
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    user: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      default:
        aliases:
          - datawatch-db

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    ports:
      - '15672:15672'  # admin UI; credentials: guest/guest
    volumes:
      - /var/lib/rabbitmq
    restart: unless-stopped
    networks:
      default:
        aliases:
          - datawatch-rabbitmq

volumes:
  db_data: {}
