# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datawatch', '0003_auto_20160904_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='Result',
        ),
    ]
