# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datawatch', '0004_auto_20160904_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged at'),
        ),
        migrations.AlterField(
            model_name='result',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_by', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged by'),
        ),
        migrations.AlterField(
            model_name='result',
            name='acknowledged_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged until'),
        ),
    ]
