# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_datawatch', '0007_result_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'permissions': (('view', 'Can view results dashboard and details'), ('acknowledge', 'Can acknowledge results'), ('config', 'Can change the configuration for results'), ('refresh', 'Can refresh results'))},
        ),
    ]
